### ISSUE TITLE
Profil Sayfası

### ISSUE THREAD

**Issue by fatihgurdal** [onuralphho/ChatAppV2#15]

**Comment by onuralphho** [comment]
*Ayarlara parola değiştirme yapısı
*Durum ekleme, ayarlardan ayrı bir yerde profil görüntüleme

**Comment by onuralphho** [comment]
Katmanlı mimariye geçişden sonraki ilk db güncellemem hata aldı. Sorunu araştırdığımda  Program.cs'in olduğu projeyle Migration yapmaya çalıştığım projenin (DataAccess) katmanlı mimari sonrası ayrılmış olmasından kaynaklandığını farkettim.

Çözüm olarak : **dotnet ef migrations add FeelingColumn --project ChatAppBackend.DataAccess --startup-project ChatAppBackend**

--project ile Migrations yapılacak projeyi --startup ile program.cs'in bulunduğu projeyi belirterek ve bu kodu parent dosyada yani .sln bulunan dosyada çalıştırdığımızda sorun ortadan kalkmış oluyor.

aynı şekilde db update işlemi için: **dotnet ef database update --project ChatAppBackend.DataAccess --startup-project ChatAppBackend**
