### ISSUE TITLE
Uygulamaya çoklu dil desteğinin verilmesi

### ISSUE THREAD

**Issue by fatihgurdal** [onuralphho/ChatAppV2#5]
tr.json
{
	"SendMessageSuccess":"Mesaj başarıyla gönderildi.",
	"LoginPasswordWrong":"Şifre yanlış",
	"10000":"Şifre yanlış",
}
en.json
{
	"SendMessageSuccess":"EN mesaj"
	"LoginPasswordWrong":"EN login mesaj",
}
ru.json
{
	"SendMessageSuccess":"RU mesaj"
	"LoginPasswordWrong":"RU login mesaj",
}

localstorage: en

const lang = readLocalStorage();
Localication.setLang(lang);

Localication.getValue("SendMessageSuccess")

**Comment by onuralphho** [comment]
React Localization, I18N araştırılacak
